# ...existing code...
# Substitua o seletor antigo pelo novo seletor de classe completa:
driver.find_element(By.CSS_SELECTOR, ".fa.fa-user.pec-polo-passivo-partes-processo.pec-botao-intimar-polo-partes-processo").click()
# ...existing code...