 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
 | sim | cancelado: sim
hermanngreb.com.br | sim | cancelado: sim
news.market.shein.com | sim | cancelado: sim
comunicacao.foodtosave.com.br | sim | cancelado: sim
emkt.pichau.com.br | sim | cancelado: sim
inf.santistadecora.com.br | sim | cancelado: sim
emails.decolar.com | sim | cancelado: sim
trade.bull-ex.com | sim | cancelado: nao
capitalizo.com.br | sim | cancelado: nao
btgpactual.com | sim | cancelado: nao
funprespjud.com.br | sim | cancelado: nao
mynt.com.br | sim | cancelado: nao
email.carrefour.com.br | sim | cancelado: nao
betnacional.bet.br | sim | cancelado: sim
emkt.ze.delivery | sim | cancelado: sim
mkt.esfera.com.vc | sim | cancelado: nao
enotasgw.com.br | sim | cancelado: nao
hotmart.com | sim | cancelado: nao
mercadolivre.com | sim | cancelado: nao
dicadehoje7.com | sim | cancelado: nao
dmcnlabs.com.br | sim | cancelado: nao
lojas.tendaatacado.com.br | sim | cancelado: sim
exclusivo.leroymerlin.com.br | sim | cancelado: nao
legale.com.br | sim | cancelado: nao
mkt.acoesgarantem.com.br | sim | cancelado: sim
studiomarciomarkkx.com.br | sim | cancelado: nao
microsoft.com | sim | cancelado: nao
greenn.com.br | sim | cancelado: nao
getmemberkit.com | sim | cancelado: nao
openrouter.ai | sim | cancelado: sim
newsolx.com.br | sim | cancelado: sim
facebookmail.com | sim | cancelado: nao
mc.buser.com.br | sim | cancelado: nao
mercadolivre.com | sim | cancelado: nao
gorilashield.com.br | sim | cancelado: nao
betfury.com | sim | cancelado: nao
e.drogaraia.com.br | sim | cancelado: nao
mail.instagram.com | sim | cancelado: nao
news2.avatrade.com | sim | cancelado: nao
kotas.com.br | sim | cancelado: nao
xpi.com.br | sim | cancelado: nao
mail.shopee.com.br | sim | cancelado: nao
legal-updates.wetransfer.com | sim | cancelado: nao
mg.hub.la | sim | cancelado: sim
suporte.donamaid.com | sim | cancelado: nao
messaging.disneyplus.com | sim | cancelado: sim
necton.com.br | sim | cancelado: nao
emkt.b3.com.br | sim | cancelado: sim
members.netflix.com | sim | cancelado: nao
email.samsclub.com.br | sim | cancelado: nao
shop.temuofficial.com | sim | cancelado: sim
pocketoption.com | sim | cancelado: nao
market.temuemail.com | sim | cancelado: nao
flybondi.com | sim | cancelado: sim
sureleveragefunding.com | sim | cancelado: sim
roboforex.com | sim | cancelado: nao
tendaatacado.com.br | sim | cancelado: nao
bringoz.com | sim | cancelado: sim
updates.asanarebel.com | sim | cancelado: sim
paxful.com | sim | cancelado: sim
myfxbook.com | sim | cancelado: nao
santander.com.br | sim | cancelado: nao
communications.mastercard.com.br | sim | cancelado: sim
email.anthropic.com | sim | cancelado: nao
a.mercadopago.com | sim | cancelado: nao
99app.com | sim | cancelado: nao
reelcrypto.com | sim | cancelado: nao
autemai.com.br | sim | cancelado: nao
e.drogasil.com.br | sim | cancelado: sim
r.mercadolivre.com.br | sim | cancelado: nao
nubank.com.br | sim | cancelado: nao
sqedit.com | sim | cancelado: nao
mail.replit.com | sim | cancelado: sim
marketing.bluechip.io | sim | cancelado: sim
betinasia.com | sim | cancelado: nao
services.betsul.bet.br | sim | cancelado: sim
mail.cosine.sh | sim | cancelado: sim
grana.capital | sim | cancelado: nao
glennharrold.com | sim | cancelado: nao
accounts.google.com | sim | cancelado: nao
monetamarkets.com | sim | cancelado: nao
vivo.com.br | sim | cancelado: sim
marketing.picpay.com | sim | cancelado: sim
mail.getninjas.com.br | sim | cancelado: sim
sportmarket.com | sim | cancelado: nao
marketing-clubedoingresso.com.br | sim | cancelado: nao
curiositystream.com | sim | cancelado: nao
relacionamento.qualidoc.com.br | sim | cancelado: nao
sicoob.com.br | sim | cancelado: sim
habitica.com | sim | cancelado: nao
steampowered.com | sim | cancelado: nao
experimentabrasil.com | sim | cancelado: sim
linkedin.com | sim | cancelado: nao
concursosfcc.com.br | sim | cancelado: nao
2000books.com | sim | cancelado: sim
fliki.ai | sim | cancelado: nao
marjosports.com.br | sim | cancelado: sim
comunicacao.inter.co | sim | cancelado: nao
campanhas.sicoob.com.br | sim | cancelado: sim
google.com | sim | cancelado: nao
m21.email.samsung.com | sim | cancelado: sim
urbanflowers.com.br | sim | cancelado: nao
violetaevoce.com.br | sim | cancelado: nao
docol.com.br | sim | cancelado: nao
spotify.com | sim | cancelado: sim
gmrpesquisa.com.br | sim | cancelado: sim
economia.gov.br | sim | cancelado: nao
newsletter.shopee.com.br | sim | cancelado: nao
service.tiktok.com | sim | cancelado: nao
contato.hapvidandi.com.br | sim | cancelado: nao
zapsign.com.br | sim | cancelado: nao
r.mercadopago.com | sim | cancelado: nao
msg.zenklub.com | sim | cancelado: sim
lastlink.com | sim | cancelado: nao
mail.keepersecurity.com | sim | cancelado: nao
quadterminal.com | sim | cancelado: nao
comms.activision.com | sim | cancelado: nao
e.fbs.com | sim | cancelado: nao
crm.fotmarkets.com | sim | cancelado: sim
news.ifood.com.br | sim | cancelado: sim
speechactors.com | sim | cancelado: nao
mail.invest.academy | sim | cancelado: sim
brasil.santander.com.br | sim | cancelado: sim
github.com | sim | cancelado: nao
paypal.com.br | sim | cancelado: nao
astronmembers.com.br | sim | cancelado: nao
pagtrust.com.br | sim | cancelado: nao
ictrading.com | sim | cancelado: nao
amazon.com | sim | cancelado: nao
novatoledo.com.br | sim | cancelado: nao
nelogica.com.br | sim | cancelado: sim
mail.blinkist.com | sim | cancelado: nao
info.octafx.com | sim | cancelado: nao
airbnb.com | sim | cancelado: nao
sales.temuemail.com | sim | cancelado: sim
xpinforma.com.br | sim | cancelado: nao
kiwify.com.br | sim | cancelado: nao
prefeitura.sp.gov.br | sim | cancelado: nao
cuoreplatform.com | sim | cancelado: nao
mail.beehiiv.com | sim | cancelado: nao
campaigns-exclusivebet.com | sim | cancelado: sim
e-mails.microsoft.com | sim | cancelado: nao
primevideo.com | sim | cancelado: nao
intermedica.com.br | sim | cancelado: nao
mail.nelogica.com.br | sim | cancelado: sim
mongodb.com | sim | cancelado: nao
voce-e.creditas.com | sim | cancelado: nao
cademi.com.br | sim | cancelado: nao
apps.sabin.com.br | sim | cancelado: nao
reidacutelaria.com.br | sim | cancelado: nao
express.sea1.medallia.com | sim | cancelado: nao
mkt-semparar.com.br | sim | cancelado: sim
inter.co | sim | cancelado: nao
hello.paybis.com | sim | cancelado: sim
n.pelando.com.br | sim | cancelado: nao
info.astropay.com | sim | cancelado: sim
a.mercadolivre.com.br | sim | cancelado: nao
e.mobifacil.com.br | sim | cancelado: sim
novidades.nubank.com.br | sim | cancelado: nao
campanha.outback.com.br | sim | cancelado: sim
oglobojn.com.br | sim | cancelado: sim
peh.adv.br | sim | cancelado: nao
sssgame88.com | sim | cancelado: nao
warren.com.br | sim | cancelado: nao
email.openai.com | sim | cancelado: sim
dooprime.net | sim | cancelado: nao
make.com | sim | cancelado: sim
comunicacao.kotas.com.br | sim | cancelado: nao
emkt.movida.com.br | sim | cancelado: sim
neemo.com.br | sim | cancelado: nao
crisfranklin.com.br | sim | cancelado: sim
pesquisas.ifood.com.br | sim | cancelado: sim
reveri.com | sim | cancelado: nao
forexstore.com | sim | cancelado: nao
accountmail.microsoft.com | sim | cancelado: nao
mercado.ifood.com.br | sim | cancelado: sim
irtrade.com.br | sim | cancelado: nao
diversainvestimentos.com.br | sim | cancelado: nao
thetown.com.br | sim | cancelado: sim
cakto.com.br | sim | cancelado: nao
xpnews.com.br | sim | cancelado: nao
mail.cacaushow.com.br | sim | cancelado: sim
myfitnesspal.com | sim | cancelado: nao
taximachine.com.br | sim | cancelado: nao
mail.betonline.ag | sim | cancelado: nao
news.teachable.com | sim | cancelado: nao
send.ultiself.com | sim | cancelado: sim
news.skrill.com | sim | cancelado: sim
themovementathlete.com | sim | cancelado: nao
cartpanda.com | sim | cancelado: nao
louisck.com | sim | cancelado: sim
pagbank.com.br | sim | cancelado: nao
xsolla.com | sim | cancelado: nao
email.github.com | sim | cancelado: nao
mail.mrjack.bet | sim | cancelado: nao
olx.com.br | sim | cancelado: nao
clubesemar.com.br | sim | cancelado: sim
ses.binance.com | sim | cancelado: nao
solucx.com.br | sim | cancelado: sim
doare.org | sim | cancelado: sim
linxnfe.com.br | sim | cancelado: nao
dooprime.com | sim | cancelado: nao
gmail.com | sim | cancelado: nao
substack.com | sim | cancelado: sim
perfectpay.com.br | sim | cancelado: sim
mariabrasileira.com.br | sim | cancelado: nao
windsurf.ai | sim | cancelado: nao
radardedividendos.com.br | sim | cancelado: nao
eduzz.com | sim | cancelado: nao
ultimate-guitar.com | sim | cancelado: nao
news.neteller.com | sim | cancelado: nao
informativoclicksophia.com.br | sim | cancelado: nao
mkt.swift.com.br | sim | cancelado: sim
info.mercadolivre.com.br | sim | cancelado: nao
fulltbet.bet.br | sim | cancelado: nao
team.mongodb.com | sim | cancelado: sim
mail.ultimate-guitar.com | sim | cancelado: sim
transactional.wiapy.com | sim | cancelado: nao
cc.eduzz.com | sim | cancelado: nao
410labs.com | sim | cancelado: nao
pensarconcursos.com | sim | cancelado: sim
satisfacaosemparar.com.br | sim | cancelado: nao
mail.bybit.com | sim | cancelado: sim
amazonmusic.com | sim | cancelado: nao
youse.com.br | sim | cancelado: nao
clickworker.com | sim | cancelado: sim
cartaotenda.com.br | sim | cancelado: nao
itau.com.br | sim | cancelado: nao
aiavalanche.com | sim | cancelado: sim
firefox.com | sim | cancelado: nao
codegpt.dev | sim | cancelado: nao
grupofleury.com.br | sim | cancelado: nao
mercadopago.com | sim | cancelado: nao
yampi-mail.com.br | sim | cancelado: nao
clickcannabis.com | sim | cancelado: nao
clicksophia.com.br | sim | cancelado: nao
neoenergiaelektro.com.br | sim | cancelado: sim
trafficadbar.com | sim | cancelado: sim
duolingo.com | sim | cancelado: nao
avaliesuacompra.com | sim | cancelado: nao
ajuda-legale.zendesk.com | sim | cancelado: nao
reinoeducacao.com | sim | cancelado: sim
wetransfer.com | sim | cancelado: sim
astropay.com | sim | cancelado: nao
sproutfi.com | sim | cancelado: nao
mail.stake.com | sim | cancelado: sim
mail.pinnacle.com | sim | cancelado: sim
thetipsterleague.com | sim | cancelado: nao
anylist.com | sim | cancelado: sim
email.f12.bet | sim | cancelado: sim
b3.com.br | sim | cancelado: nao
mail-tokiomarine.com.br | sim | cancelado: sim
kucoin.com | sim | cancelado: sim
comgas.com.br | sim | cancelado: sim
mkt.parafuzo.com | sim | cancelado: sim
cf.natura.com | sim | cancelado: sim
clubbingbuy.com | sim | cancelado: nao
dsfnet.com.br | sim | cancelado: sim
kirvano.com | sim | cancelado: nao
myprofitweb.com | sim | cancelado: nao
soundiiz.com | sim | cancelado: sim
hurst.capital | sim | cancelado: sim
mail.anthropic.com | sim | cancelado: nao
relay.firefox.com | sim | cancelado: nao
parsehub.com | sim | cancelado: nao
ticto.com.br | sim | cancelado: nao
automatiklabs.com.br | sim | cancelado: nao
freetts.com | sim | cancelado: nao
tm.openai.com | sim | cancelado: nao
guitarmastery.net | sim | cancelado: nao
matchbook.com | sim | cancelado: nao
mail.disneyplus.com | sim | cancelado: nao
minhaclaro.com.br | sim | cancelado: sim
info.growthsupplements.com.br | sim | cancelado: sim
bancodaycovaleventos.com.br | sim | cancelado: nao
terabox.com | sim | cancelado: sim
hapvida.com.br | sim | cancelado: nao
explore.pinterest.com | sim | cancelado: nao
buser.com.br | sim | cancelado: nao
webby.app | sim | cancelado: nao
esportesdasorte.com | sim | cancelado: nao
mail.herospark.com | sim | cancelado: nao
edools.com | sim | cancelado: nao
estrelabet.com | sim | cancelado: nao
appmcdonalds.com | sim | cancelado: nao
mail.threads.net | sim | cancelado: nao
oliveiratrust.com.br | sim | cancelado: nao
picpay.com | sim | cancelado: nao
email.genialinvestimentos.com.br | sim | cancelado: sim
bet-bra.com | sim | cancelado: nao
deliverydireto.co | sim | cancelado: nao
mx1.casadeapostas.com | sim | cancelado: nao
20bet.com | sim | cancelado: sim
betpix365.com | sim | cancelado: nao
notifications.lumosity.com | sim | cancelado: sim
dietbox.me | sim | cancelado: sim
tempobet.com | sim | cancelado: nao
mivest.io | sim | cancelado: nao
promo.ifood.com.br | sim | cancelado: sim
cartaotenda.inf.br | sim | cancelado: nao
glovoapp.com | sim | cancelado: nao
sssgame77.com | sim | cancelado: nao
mercadolivre.com | sim | cancelado: nao
m88.com | sim | cancelado: sim
email.tryleaply.com | sim | cancelado: sim
americanas.com.br | sim | cancelado: nao
p4f.com | sim | cancelado: sim
somosbiu.com | sim | cancelado: nao
allianzbrasil.com.br | sim | cancelado: sim
news.belezanaweb.com.br | sim | cancelado: sim
notify.betmaster.email | sim | cancelado: nao
jacssonsantos.com.br | sim | cancelado: nao
arenatribe.com | sim | cancelado: nao
hello.rappi.com.ar | sim | cancelado: nao
trt2.jus.br | sim | cancelado: nao
publica.inf.br | sim | cancelado: nao
vtexcommerce.com.br | sim | cancelado: nao
theflipper.com.br | sim | cancelado: sim
order.temu.com | sim | cancelado: sim
bradescosegurosdigital.com.br | sim | cancelado: sim
mail.sportsbetting.ag | sim | cancelado: sim
clicksign.com | sim | cancelado: nao
notazz.com | sim | cancelado: nao
mail.crunchyroll.com | sim | cancelado: nao
telefonica.com | sim | cancelado: nao
rivalo.com | sim | cancelado: sim
magazineluiza.com.br | sim | cancelado: nao
hello.curiositystream.com | sim | cancelado: nao
voc.allianz.com.br | sim | cancelado: nao
n1bet.com | sim | cancelado: nao
pakman.com.br | sim | cancelado: sim
muchbetter.com | sim | cancelado: sim
safety4me.com | sim | cancelado: nao
mevosaude.com.br | sim | cancelado: nao
info.asanarebel.com | sim | cancelado: sim
e.farmaciadpsp.com.br | sim | cancelado: nao
fcc.org.br | sim | cancelado: nao
clubedoingresso.com.br | sim | cancelado: nao
doppus.com | sim | cancelado: nao
folhadespaulo.com.br | sim | cancelado: sim
nfe.io | sim | cancelado: nao
seupedido.casasbahia.com.br | sim | cancelado: nao
betano.com | sim | cancelado: nao
surebet.com | sim | cancelado: sim
mail.betfair.com | sim | cancelado: nao
accountprotection.microsoft.com | sim | cancelado: nao
apostadevalor.com.br | sim | cancelado: sim
email.superbet.com | sim | cancelado: sim
gamerswallet.com.br | sim | cancelado: nao
monetizze.com.br | sim | cancelado: nao
semarentrega.com.br | sim | cancelado: nao
news.petlove.com.br | sim | cancelado: sim
campaigns-br.betano.com | sim | cancelado: nao
mail.bwin.com | sim | cancelado: nao
orders.viagogo.com | sim | cancelado: nao
mail.sportingbet.com | sim | cancelado: nao
bybit.com | sim | cancelado: sim
snapchat.com | sim | cancelado: nao
verify.snapchat.com | sim | cancelado: nao
doctoralia.com | sim | cancelado: nao
royalpanda.com | sim | cancelado: sim
mercadodiferente.com.br | sim | cancelado: nao
barueri.sp.gov.br | sim | cancelado: nao
mktcasadeapostas.com.br | sim | cancelado: nao
lembretedecadastro.com | sim | cancelado: sim
novidadesclicksophia.com.br | sim | cancelado: sim
mercadolibre.com | sim | cancelado: nao
myorder.soudaki.com | sim | cancelado: nao
miranaindependencia.com.br | sim | cancelado: sim
e.manipulacao.drogasil.com.br | sim | cancelado: sim
tmbfinanciamento.com.br | sim | cancelado: nao
statusinvest.com.br | sim | cancelado: nao
buyticketbrasil.com | sim | cancelado: nao
ola.soujusto.com.br | sim | cancelado: nao
perfectmoney.com | sim | cancelado: nao
sabesp.com.br | sim | cancelado: nao
fulltrader.site | sim | cancelado: nao
rivalry.com | sim | cancelado: nao
oldensports.com.br | sim | cancelado: nao
petlovesaude.zendesk.com | sim | cancelado: nao
bancointer.com.br | sim | cancelado: nao
info.petlove.com.br | sim | cancelado: nao
novidades.petz.com.br | sim | cancelado: sim
marketing.meliuz.com.br | sim | cancelado: sim
icedrive.net | sim | cancelado: nao
petlovesaude.com.br | sim | cancelado: nao
cdi.com.br | sim | cancelado: nao
email.ticketmaster.com.br | sim | cancelado: sim
promocaosonda.com.br | sim | cancelado: nao
support.whatsapp.com | sim | cancelado: nao
petlove.com.br | sim | cancelado: nao
keepersecurity.com | sim | cancelado: nao
relacionamento2.allianzseguros.com.br | sim | cancelado: nao
communications.paypal.com | sim | cancelado: nao
lbv.org.br | sim | cancelado: nao
account.tiktok.com | sim | cancelado: nao
relacionamento.inter.co | sim | cancelado: sim
hello.rappi.com.mx | sim | cancelado: sim
mail.santanderimobiliario.com.br | sim | cancelado: nao
trocafone.com | sim | cancelado: nao
totallconcierge.com.br | sim | cancelado: nao
e.racebets.com | sim | cancelado: nao
drogaraia.com.br | sim | cancelado: nao
creditas.com.br | sim | cancelado: nao
opcoes.net.br | sim | cancelado: nao
neteller.com | sim | cancelado: nao
comunicacao.meliuz.com.br | sim | cancelado: sim
mail.ditobet.ladesk.com | sim | cancelado: nao
marketing.sulamerica.com.br | sim | cancelado: sim
catarse.me | sim | cancelado: nao
info.trustvox.com.br | sim | cancelado: nao
atendimento.servicos.gov.br | sim | cancelado: nao
amaissaude.com.br | sim | cancelado: nao
dpsp.movidesk.com | sim | cancelado: nao
mailer.888sport.com | sim | cancelado: nao
grupofolha.com.br | sim | cancelado: nao
betvictor.com | sim | cancelado: nao
promo.matchbook.com | sim | cancelado: nao
email.betsson.com | sim | cancelado: nao
fadc.org.br | sim | cancelado: nao
rappi.com | sim | cancelado: nao
mercadolivre.com | sim | cancelado: nao
mkt.mizuno.com.br | sim | cancelado: sim
mail.descorcha.com | sim | cancelado: nao
hapvidasaude.com.br | sim | cancelado: sim
newsletter.vivaldi.com | sim | cancelado: nao
email.betsafe.com | sim | cancelado: nao
playpix.com | sim | cancelado: nao
hypnosisaudio.com | sim | cancelado: sim
rappimail.com | sim | cancelado: sim
bigflash.com.br | sim | cancelado: nao
investflex.com.br | sim | cancelado: sim
quinto.com.br | sim | cancelado: nao
unindosonhos.com.br | sim | cancelado: nao
emailmkt.legale.com.br | sim | cancelado: sim
news.amedigital.com | sim | cancelado: nao
email.svc.sympla.com.br | sim | cancelado: sim
edpbr.com.br | sim | cancelado: nao
soujusto.com.br | sim | cancelado: nao
nfendd.com.br | sim | cancelado: nao
skrill.com | sim | cancelado: nao
smtplw-02.com | sim | cancelado: nao
iqoption.com | sim | cancelado: nao
communication.microsoft.com | sim | cancelado: nao
appen.com | sim | cancelado: nao
myfamilycinema.com | sim | cancelado: sim
fundacao.bradesco | sim | cancelado: nao
mail.shopee.com.my | sim | cancelado: nao
factory4.com.br | sim | cancelado: sim
mkt.pagbank.com.br | sim | cancelado: sim
notifications.deezer.com | sim | cancelado: nao
exclusivebet.com | sim | cancelado: nao
betfury.io | sim | cancelado: sim
ontick.com.br | sim | cancelado: sim
todayistheday.app | sim | cancelado: sim
directmail2.binance.com | sim | cancelado: nao
elevateapp.com | sim | cancelado: nao
youtube.com | sim | cancelado: sim
t.ingresso.com | sim | cancelado: nao
donamaid.com | sim | cancelado: nao
acoesgarantem.com.br | sim | cancelado: nao
account.netflix.com | sim | cancelado: nao
forexbestrobots.com | sim | cancelado: nao
rebatekingfx.com | sim | cancelado: sim
aliabdaal.com | sim | cancelado: nao
cx.takaoka.com.br | sim | cancelado: nao
rollbit.com | sim | cancelado: nao
senado.leg.br | sim | cancelado: nao
email.m88promo.com | sim | cancelado: nao
millionaviator.com | sim | cancelado: nao
priority.facebookmail.com | sim | cancelado: nao
redecamara.com.br | sim | cancelado: nao
dasa-mail.com | sim | cancelado: sim
rockinrio.com | sim | cancelado: sim
ct.vtex.com.br | sim | cancelado: nao
infinityforexfunds.com | sim | cancelado: nao
panoramamoveis.com.br | sim | cancelado: nao
comunicacao.bancointer.com.br | sim | cancelado: nao
bitsgap.com | sim | cancelado: sim
todoist.com | sim | cancelado: nao
e.udemymail.com | sim | cancelado: nao
comunicacao.icatuseguros.com.br | sim | cancelado: nao
lojongapp.com | sim | cancelado: sim
suno.com.br | sim | cancelado: sim
news.sleepcycle.com | sim | cancelado: sim
nongams.com | sim | cancelado: nao
effecto.app | sim | cancelado: sim
icmarkets.com | sim | cancelado: nao
email2.microsoft.com | sim | cancelado: nao
auteminvestimentos.com.br | sim | cancelado: nao
hello.soudaki.com | sim | cancelado: nao
info.emprestimosim.com.br | sim | cancelado: nao
pravoce.petz.com.br | sim | cancelado: sim
danillofratta.com.br | sim | cancelado: nao
sbobet.com | sim | cancelado: nao
vakinha.com.br | sim | cancelado: nao
casino.guru | sim | cancelado: nao
m.lastpass.com | sim | cancelado: nao
contato.alfa.com.br | sim | cancelado: sim
mkt.ze.delivery | sim | cancelado: nao
informativocertisign.com.br | sim | cancelado: sim
boradetop.com.br | sim | cancelado: nao
mail.starplus.com | sim | cancelado: nao
informacliente.com.br | sim | cancelado: nao
diskchurrasqueiro.com.br | sim | cancelado: nao
sent.expressoluxo.com.br | sim | cancelado: nao
ticketmaster.com.br | sim | cancelado: nao
email.mrjack.bet | sim | cancelado: nao
zenklub.com | sim | cancelado: nao
